module Constants
  PHOTOSET_NOTPROCESSED = 0
  PHOTOSET_PROCESSING   = 1
  PHOTOSET_PROCESSED    = 2

  PHOTO_NOTPROCESSED  = 0
  PHOTO_PROCESSING    = 1
  PHOTO_UPLOADING     = 11
  PHOTO_PROCESSED     = 2
  PHOTO_FAILED        = 42
  PHOTO_ACCESS_DENIED = 400
  

  SOURCE_FLICKR = 'F'
  SOURCE_PICASA = 'P'
end