development:
  host: localhost
  database: flickr2facebook_development

test:
  host: localhost
  database: flickr2facebook_test

# set these environment variables on your prod server
production:

  host: localhost
  database: flickr2facebook_production
