development:
  client_id: '258618021508.apps.googleusercontent.com'
  client_secret: '1Rd6RsL2YnPYAE-_Wrcjm79i'

production:
  client_id: '741016501006.apps.googleusercontent.com'
  client_secret: 'dNPZw8SNeUR2B-us3QePkHlC'
